server :
  port : 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
    username: zyh
    password: zyh081
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

  devtools:
    restart:
      enabled: false

  mvc:
    pathmatch:
      #swagger3.0与高版本springboot不兼容解决办法
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.example.domain

springfox:
  documentation:
    enabled: true
    swagger-ui:
      enabled: true
    open-api:
      v3:
        path: /v3/api-docs